version: '3.8'

services:
  winnie:
    container_name: winnie
    restart: always
    build:
      context: .
      target: production
    ports:
      - 22:3555
      - 8080:8080
    env_file:
      - .env
